service: wl-backend-functions 
frameworkVersion: '3'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  memorySize: 1024
  timeout: 29

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  asosmin:
    handler: kma-scraper/handler.asosminweather
    events:
      - httpApi:
          path: /asosmin/{datetime}
          method: get